// Source : https://leetcode.com/problems/find-the-difference
// Date : 2024-01-05

/*
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
 
*/

#include <string>
#include <unordered_set>
using namespace std;

class Solution 
{
public:
    char findTheDifference(string s, string t) 
    {
        int answer = 0;
        
        for (char c : s + t)
        {
            answer ^= c;
        }
        
        return answer;
    }
};